//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int AuthorID { get; set; }
        public string AuthorUserName { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
        public string AuthorEmal { get; set; }
        public Nullable<System.DateTime> AuthorDOB { get; set; }
        public string AuthorPic { get; set; }
        public string AuthorBio { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
    }
}
