//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public int PostID { get; set; }
        public int CommentAuthor { get; set; }
        public System.DateTime CommentedOn { get; set; }
        public string CommentText { get; set; }
        public string CommentPicture { get; set; }
        public int CommentLikes { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
