//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int PostID { get; set; }
        public int AuthorID { get; set; }
        public string PostTitle { get; set; }
        public string PostAuthor { get; set; }
        public System.DateTime PostedOn { get; set; }
        public string PostText { get; set; }
        public string PostPicture { get; set; }
        public string PostTags { get; set; }
        public int PostLikes { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
